### PR TITLE
Avoids committing intermediate files

### PR DESCRIPTION
**Pull request by amarvin**

### CODE REVIEW

**Review by jocfico — CHANGES_REQUESTED** [review]
These look like Xpress Workbench changes.  
It needs to be *.zip because workbench generates it from the named Mosel file but I generate the zip from a local shell script.
Also the .bim file only needs to be ignored when inside the 'source' folder. The root *.bim file I need to be able to upload.
Thanks for contributing!

**Comment by amarvin** [comment]
Thanks! I love the idea of this new GitHub repo, and have really been enjoying all the FICO Insight upgrades! Looking forward to collaborate here :)

Hmm, but any *.bim files are created when the Mosel script is compiled, so you'd have a new *.bim versions each time you change a Mosel file. Why store it twice? Note that just because the bim is ignored by Git doesn't mean that you won't have the file on your local computer for publishing and testing.

**Comment by jocfico** [comment]
Yes, it is a new departure for us in the Insight dev team and we are keen to cooperate with the wider optimization community.

I'm not sure I follow you Alex. If a Mosel file is changed and compiled to a .bim file in the source folder then it doesn't need to be committed to the repository. If the .bim file changes in the root directory then I would want that to be committed.  The .bim file can have multiple changes before it is committed. 

That is how I see it. Do you have another use case that I am missing?

**Comment by amarvin** [comment]
I publish my app using Workbench, so maybe my procedure is different than yours. In my procedure, publishing the app creates a new .bim file in the root folder each time that is a compiled version of the app's Mosel scripts, so there's no reason to commit the .bim file on Git.

**Comment by jocfico** [comment]
Yeah that makes sense Alex. That's a problem with always compiling the mosel file whether there are changes or not. I will have a chat with the developer of Workbench to see if there is a workaround.

**Comment by amarvin** [comment]
Oh, I don't see it as a problem at all. The workflow with Workbench is very easy. I was just trying to help you from commiting files into your repo that are redundant, like the .bim files.

**Comment by jocfico** [comment]
OK, it isn't a problem for me because I compile from the command line only when I have made changes. But part of my job is to think about minutiae like this. Workbench doesn't currently take account of this effect and I think we need to. I will talk to Chris next week to see how best to resolve this.

**Comment by amarvin** [comment]
Try deleting the .bim file, then running your command-line compile process to see if it still successfully creates the Zip file that can be deployed successfully on FICO Insight. I think that it will work. If so, then no need to commit the .bim file to Git.

**Comment by jocfico** [comment]
Ah I see what you are talking about. If you open this app from Workbench then yes, it will generate the .bim file when you publish. The reason I put the .bim file in is that you can download the zip of this repository and import it straight into Insight and have a working app. You could enable local files mode and start editing the views without having to do anything with the model. More likely people will copy vdl files into their own project for the extensions they want to use. Like you say it's not a big issue but I still need to be able to commit the bim file if I need to make any changes.

**Comment by amarvin** [comment]
Good point. I'll change the commit to include the *.bim.

**Review by jocfico — APPROVED** [review]
I think that works for now. Thanks Alex

**Pull request merged**
